import QtQuick
import Quickshell
import Quickshell.Io
import qs.Commons
import qs.Ui

// Bar widget + popup for the 10-band PipeWire equalizer.
//
// State lives in ~/.config/omarchy/eq.json and the graph is generated by
// `omarchy-eq`, so this panel is only a face on that CLI: it reads gains with
// `omarchy-eq get` and writes them back with `omarchy-eq set`. Nothing here
// owns audio state, which keeps the CLI usable on its own and means a broken
// panel cannot leave the filter-chain in a weird state.
Panel {
  id: root
  moduleName: "io.github.bitta-boo.equalizer"
  // No IpcHandler of our own: the base would register one for this id and a
  // clash there stops the widget being built at all.
  manageIpc: false

  // The bar gives the widget its slot from the child's implicit size.
  implicitWidth: button.implicitWidth
  implicitHeight: button.implicitHeight

  readonly property var bandLabels: ["31", "62", "125", "250", "500", "1k", "2k", "4k", "8k", "16k"]
  property var gains: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  property bool enabled: true
  property real preamp: 0
  property bool surround: false
  property string activePreset: ""
  // Must mirror the headroom rule in omarchy-eq or the header reports a figure
  // the filter is not actually using. Surround is not part of that rule: the
  // widener passes centred content at unity, so it is not charged headroom.
  readonly property real autoHeadroom: {
    var mx = 0
    for (var i = 0; i < gains.length; i++) if (gains[i] > mx) mx = gains[i]
    return -mx + preamp   // surround is not charged headroom, see omarchy-eq
  }
  property bool loaded: false
  property bool backendMissing: false
  readonly property int labelSize: Style.font.bodySmall

  readonly property color foreground: bar ? bar.foreground : Color.foreground
  readonly property color dim: Qt.darker(foreground, 1.55)

  function reload() { root.launch(readProc, readDeadline, [root.eqBin, "get"]) }

  // ---- process invocation -------------------------------------------------
  //
  // Every child process is launched from an absolute path with an explicit
  // environment, a hard deadline, and a bounded, schema-checked output. The
  // inherited PATH is not consulted, so nothing a caller puts on PATH can
  // decide which binary this widget runs.
  readonly property string home: Quickshell.env("HOME") || ""
  readonly property string eqBin: home + "/.local/bin/omarchy-eq"

  // Minimal environment. systemctl --user and pw-cli need the session bus and
  // the runtime directory; nothing else is inherited.
  readonly property var procEnv: ({
    "PATH": "/usr/local/bin:/usr/bin:/bin",
    "HOME": home,
    "XDG_RUNTIME_DIR": Quickshell.env("XDG_RUNTIME_DIR") || "",
    "DBUS_SESSION_BUS_ADDRESS": Quickshell.env("DBUS_SESSION_BUS_ADDRESS") || ""
  })

  readonly property int readDeadlineMs: 2500    // `get` only reads a small file
  readonly property int cmdDeadlineMs: 8000     // writes may talk to pipewire
  readonly property int maxOutputBytes: 65536   // `get` is well under 1 KiB

  // SIGTERM first, then clear `running`. Signalling is what actually terminates
  // a hung producer; clearing `running` alone only detaches Quickshell's side.
  readonly property int sigTerm: 15
  function killProc(proc) {
    if (!proc.running) return
    proc.signal(root.sigTerm)
    proc.running = false
  }

  // Always arm the deadline before starting, never from onRunningChanged: if the
  // executable does not exist, `running` never transitions to true, so a handler
  // hung off it would never arm the very timeout meant to catch that case.
  function launch(proc, deadline, args) {
    proc.command = args
    deadline.restart()
    proc.running = true
  }

  // A missing executable is detected here rather than by an exit code: when the
  // binary does not exist Quickshell's Process never emits `exited` at all, so
  // the read deadline is what tells us the backend is not installed.
  Timer {
    id: readDeadline
    interval: root.readDeadlineMs
    onTriggered: {
      root.killProc(readProc)
      root.backendMissing = true
      root.loaded = false
    }
  }
  Timer { id: writeDeadline;    interval: root.cmdDeadlineMs; onTriggered: root.killProc(writeProc) }
  Timer { id: preampDeadline;   interval: root.cmdDeadlineMs; onTriggered: root.killProc(preampProc) }
  Timer { id: toggleDeadline;   interval: root.cmdDeadlineMs; onTriggered: root.killProc(toggleProc) }
  Timer { id: presetDeadline;   interval: root.cmdDeadlineMs; onTriggered: root.killProc(presetProc) }
  Timer { id: surroundDeadline; interval: root.cmdDeadlineMs; onTriggered: root.killProc(surroundProc) }

  // Rejects anything that is not the exact shape `omarchy-eq get` produces, so
  // a corrupted or oversized state file cannot drive the UI.
  function parseState(text) {
    if (typeof text !== "string" || text.length === 0 || text.length > root.maxOutputBytes) return null
    var d
    try { d = JSON.parse(text) } catch (e) { return null }
    if (!d || typeof d !== "object" || !Array.isArray(d.gains) || d.gains.length !== 10) return null
    var g = []
    for (var i = 0; i < 10; i++) {
      var v = d.gains[i]
      if (typeof v !== "number" || !isFinite(v) || v < -12 || v > 12) return null
      g.push(v)
    }
    var pre = (typeof d.preamp === "number" && isFinite(d.preamp)) ? Math.max(-12, Math.min(12, d.preamp)) : 0
    var preset = (typeof d.preset === "string" && d.preset.length <= 32) ? d.preset : ""
    return { gains: g, preamp: pre, surround: !!d.surround, enabled: !!d.enabled, preset: preset }
  }

  Process {
    id: readProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: function(exitCode) {
      readDeadline.stop()
      // It launched, so it exists. A non-zero exit means installed-but-failing,
      // which is a different state from not installed.
      root.backendMissing = false
      if (exitCode !== 0) root.loaded = false
    }
    stdout: StdioCollector {
      onStreamFinished: {
        var d = root.parseState(text)
        if (d === null) { root.loaded = false; return }
        root.gains = d.gains
        root.preamp = d.preamp
        root.surround = d.surround
        root.activePreset = d.preset
        root.enabled = d.enabled
        root.loaded = true
      }
    }
  }

  // Writes are debounced only lightly. `omarchy-eq set` pushes the value into
  // the running filter with pw-cli instead of restarting the service, so a
  // change is inaudible-in-progress rather than dropping the sink.
  property int pendingBand: -1
  property real pendingValue: 0

  function commit(index, value) {
    // Update the model immediately, not just on the next read. The slider's
    // `value` is bound to gains[index]; PanelSlider snaps liveValue back to
    // `value` when the drag ends, so leaving the old number here makes the knob
    // visibly jump back to where it started even though the write succeeded.
    var next = gains.slice()
    next[index] = Math.round(value * 2) / 2      // match the 0.5 dB step
    gains = next
    activePreset = "custom"
    pendingBand = index
    pendingValue = next[index]
    writeTimer.restart()
  }

  Timer {
    id: writeTimer
    interval: 80
    onTriggered: {
      if (root.pendingBand < 0) return
      root.launch(writeProc, writeDeadline, [root.eqBin, "set", String(root.pendingBand), String(Math.round(root.pendingValue * 10) / 10)])
      root.pendingBand = -1
    }
  }

  // No reload on completion: `commit` has already put the value in `gains`, and
  // re-reading would race a drag still in progress and snap the knob backwards.
  Process {
    id: writeProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: writeDeadline.stop()
  }

  property real pendingPreamp: 0
  function commitPreamp(v) {
    preamp = Math.round(v * 2) / 2
    pendingPreamp = preamp
    preampTimer.restart()
  }
  Timer {
    id: preampTimer
    interval: 80
    onTriggered: {
      root.launch(preampProc, preampDeadline, [root.eqBin, "preamp", String(root.pendingPreamp)])
    }
  }
  Process {
    id: preampProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: preampDeadline.stop()
  }

  Process {
    id: toggleProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: { toggleDeadline.stop(); root.reload() }
  }

  Process {
    id: presetProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: { presetDeadline.stop(); root.reload() }
  }

  Process {
    id: surroundProc
    clearEnvironment: true
    environment: root.procEnv
    onExited: { surroundDeadline.stop(); root.reload() }
  }

  // Explicit teardown: every child is sent SIGTERM and every timer stopped when
  // the widget is destroyed, rather than relying on a process ending by itself
  // or a timer firing against an item that is already gone.
  Component.onDestruction: {
    var procs = [readProc, writeProc, preampProc, toggleProc, presetProc, surroundProc]
    for (var i = 0; i < procs.length; i++) {
      root.killProc(procs[i])
    }
    var timers = [readDeadline, writeDeadline, preampDeadline, toggleDeadline,
                  presetDeadline, surroundDeadline, writeTimer, preampTimer]
    for (var j = 0; j < timers.length; j++) timers[j].stop()
  }

  Component.onCompleted: reload()
  onOpenedChanged: if (opened) reload()

  Component {
    id: eqSwitchComponent
    ToggleSwitch {
      id: eqSwitch
      checked: root.enabled
      foreground: hero.foreground
      onToggled: {
        root.launch(toggleProc, toggleDeadline, [root.eqBin, root.enabled ? "off" : "on"])
      }
      PanelToolTip {
        visible: eqSwitch.containsMouse
        text: root.enabled ? "Bypass the equalizer" : "Enable the equalizer"
      }
    }
  }


  BarIconButton {
    id: button
    anchors.fill: parent
    bar: root.bar
    // nf-md-tune_vertical_variant: three vertical sliders. Rendered by the
    // bar's own OpticalGlyph, same path every first-party widget uses, rather
    // than hand-drawing an icon.
    // nf-fa-sliders, same glyph the hero uses; dimmed when bypassed.
    text: "\uf1de"
    opacity: (root.enabled && !root.backendMissing) ? 1.0 : 0.6
    onPressed: function(buttonCode) {
      if (buttonCode === Qt.RightButton) {
        root.launch(toggleProc, toggleDeadline, [root.eqBin, root.enabled ? "off" : "on"])
      } else {
        root.toggle()
      }
    }
  }

  KeyboardPanel {
    id: panel
    anchorItem: button
    owner: root
    bar: root.bar
    open: root.opened
    focusTarget: keyCatcher
    contentWidth: panel.fittedContentWidth(Style.space(360))
    contentHeight: panel.fittedContentHeight(column.implicitHeight, Style.space(620))

    PanelKeyCatcher {
      id: keyCatcher
      anchors.fill: parent
      onCloseRequested: root.close()
    }

    Column {
      id: column
      anchors.left: parent.left
      anchors.right: parent.right
      anchors.top: parent.top
      spacing: Style.spacing.sm

      // House style: hero header with the on/off as a trailing ToggleSwitch,
      // matching the Bluetooth and Dropbox panels, rather than a Disable button.
      PanelHero {
        id: hero
        width: column.width
        title: "Equalizer"
        meta: root.backendMissing
              ? "NOT INSTALLED"
              : root.enabled
                ? ((root.autoHeadroom >= 0 ? "+" : "") + root.autoHeadroom.toFixed(1) + " DB HEADROOM")
                : "BYPASSED"
        iconOpacity: (root.enabled && !root.backendMissing) ? 1.0 : 0.5
        iconComponent: Component {
          Text {
            text: "\uf1de"                       // nf-fa-sliders
            font.family: Style.font.family
            font.pixelSize: Style.font.display
            color: hero.foreground
          }
        }
        trailingControl: root.backendMissing ? null : eqSwitchComponent
      }

      // Expected right after `omarchy plugin add` without install.sh: the widget
      // is installed but the PipeWire filter, the service and the CLI it drives
      // are not. Name the exact command rather than just reporting breakage.
      Column {
        width: column.width
        visible: root.backendMissing
        spacing: Style.spacing.sm

        PanelSeparator { foreground: root.foreground }

        Text {
          width: column.width
          text: "The equalizer backend is not installed, so there is nothing to control yet.\n\n"
                + "Run  ~/.config/omarchy/plugins/" + root.moduleName + "/install.sh\n\n"
                + "then reopen this panel."
          color: root.dim
          font.family: Style.font.family
          font.pixelSize: Style.font.body
          wrapMode: Text.WordWrap
        }
      }

      Column {
        id: body
        width: column.width
        visible: !root.backendMissing
        spacing: Style.spacing.sm

        PanelSeparator { foreground: root.foreground }

        // Manual level offset. Headroom is otherwise set automatically to
        // -max(boost); raising this trades that headroom back for loudness.
        Item {
          width: column.width
          height: Style.space(30)

          Text {
            id: preLabel
            anchors.left: parent.left
            anchors.verticalCenter: parent.verticalCenter
            width: Style.space(34)
            text: "pre"
            color: root.foreground
            opacity: root.enabled ? 0.85 : 0.4
            font.pixelSize: root.labelSize
          }

          PanelSlider {
            id: preSlider
            bar: root.bar
            anchors.left: preLabel.right
            anchors.right: preReadout.left
            anchors.rightMargin: Style.spacing.sm
            anchors.verticalCenter: parent.verticalCenter
            minimum: -12
            maximum: 12
            step: 0.5
            tickCount: 5
            value: root.loaded ? root.preamp : 0
            opacity: root.enabled ? 1 : 0.45
            onMoved: function(v) { root.commitPreamp(v) }
            onReleased: function(v) { root.commitPreamp(v) }
            // Right-click resets to 0 = fully automatic headroom. Landing exactly
            // on the centre by dragging is fiddly.
            onRightClicked: root.commitPreamp(0)
          }

          Text {
            id: preReadout
            anchors.right: parent.right
            anchors.verticalCenter: parent.verticalCenter
            width: Style.space(46)
            horizontalAlignment: Text.AlignRight
            text: (preSlider.liveValue >= 0 ? "+" : "") + preSlider.liveValue.toFixed(1)
            color: root.foreground
            opacity: root.enabled ? 0.7 : 0.35
            font.pixelSize: root.labelSize
          }
        }

        PanelSeparator { foreground: root.foreground }

        Repeater {
          model: root.bandLabels.length

          Item {
            width: column.width
            height: Style.space(30)

            Text {
              id: label
              anchors.left: parent.left
              anchors.verticalCenter: parent.verticalCenter
              width: Style.space(34)
              text: root.bandLabels[index]
              color: root.foreground
              opacity: root.enabled ? 0.85 : 0.4
              font.pixelSize: root.labelSize
            }

            PanelSlider {
              id: slider
              bar: root.bar
              anchors.left: label.right
              anchors.right: readout.left
              anchors.rightMargin: Style.spacing.sm
              anchors.verticalCenter: parent.verticalCenter
              minimum: -12
              maximum: 12
              step: 0.5
              tickCount: 5              // centre notch marks 0 dB
              value: root.loaded ? root.gains[index] : 0
              opacity: root.enabled ? 1 : 0.45
              onMoved: function(v) { root.commit(index, v) }
              onReleased: function(v) { root.commit(index, v) }
              onRightClicked: root.commit(index, 0)
            }

            Text {
              id: readout
              anchors.right: parent.right
              anchors.verticalCenter: parent.verticalCenter
              width: Style.space(46)
              horizontalAlignment: Text.AlignRight
              text: (slider.liveValue >= 0 ? "+" : "") + slider.liveValue.toFixed(1)
              color: root.foreground
              opacity: root.enabled ? 0.7 : 0.35
              font.pixelSize: root.labelSize
            }
          }
        }

        PanelSeparator { foreground: root.foreground }


        // Stereo widening. Implemented as a mid/side stage whose width is a live
        // mixer gain, so this flips instantly and the bands keep working.
        Toggle {
          width: column.width
          label: "Surround"
          checked: root.surround
          foreground: root.foreground
          onClicked: {
            root.launch(surroundProc, surroundDeadline, [root.eqBin, "surround", root.surround ? "off" : "on"])
          }
        }

        PanelSeparator { foreground: root.foreground }

        // Flow rather than Row: the preset buttons now exceed one row at this
        // panel width, and Row would clip rather than wrap.
        Flow {
          width: column.width
          spacing: Style.spacing.sm

          Button {
            text: "Flat"
            foreground: root.foreground
            bordered: true
            selected: root.activePreset === "flat"
            // Zero the bands *and* the manual preamp, so one click is a complete
            // return to neutral rather than leaving a stray offset behind.
            onClicked: {
              root.activePreset = "flat"
              root.commitPreamp(0)
              root.launch(presetProc, presetDeadline, [root.eqBin, "preset", "flat"])
            }
          }
          Button {
            text: "Treble"
            foreground: root.foreground
            bordered: true
            selected: root.activePreset === "treble"
            onClicked: { root.activePreset = "treble"; root.launch(presetProc, presetDeadline, [root.eqBin, "preset", "treble"]) }
          }
          Button {
            text: "Gaming"
            foreground: root.foreground
            bordered: true
            selected: root.activePreset === "gaming"
            onClicked: { root.activePreset = "gaming"; root.launch(presetProc, presetDeadline, [root.eqBin, "preset", "gaming"]) }
          }
          Button {
            text: "Vocal"
            foreground: root.foreground
            bordered: true
            selected: root.activePreset === "vocal"
            onClicked: { root.activePreset = "vocal"; root.launch(presetProc, presetDeadline, [root.eqBin, "preset", "vocal"]) }
          }
          // Recalls whatever was last dialled in by hand. Editing any band writes
          // into this slot, so switching away and back restores those changes.
          Button {
            text: "Custom"
            foreground: root.foreground
            bordered: true
            selected: root.activePreset === "custom"
            onClicked: { root.activePreset = "custom"; root.launch(presetProc, presetDeadline, [root.eqBin, "preset", "custom"]) }
          }

        }
      }
    }
  }
}
